"""initial_migration

Revision ID: ee03c1329669
Revises: 
Create Date: 2025-08-06 12:42:53.639807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee03c1329669'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('configuraciones', sa.JSON(), nullable=True),
    sa.Column('did_whatsapp', sa.String(length=50), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinicas_did_whatsapp'), 'clinicas', ['did_whatsapp'], unique=True)
    op.create_index(op.f('ix_clinicas_id'), 'clinicas', ['id'], unique=False)
    op.create_index(op.f('ix_clinicas_nombre'), 'clinicas', ['nombre'], unique=False)
    op.create_table('especialidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('preparacion_previa', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_especialidad_nombre', 'especialidades', ['nombre'], unique=False)
    op.create_index(op.f('ix_especialidades_id'), 'especialidades', ['id'], unique=False)
    op.create_index(op.f('ix_especialidades_nombre'), 'especialidades', ['nombre'], unique=False)
    op.create_table('logs_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('respuesta_ia', sa.Text(), nullable=False),
    sa.Column('confianza', sa.String(length=20), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('metadatos', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_log_fecha_confianza', 'logs_ia', ['fecha', 'confianza'], unique=False)
    op.create_index(op.f('ix_logs_ia_fecha'), 'logs_ia', ['fecha'], unique=False)
    op.create_index(op.f('ix_logs_ia_id'), 'logs_ia', ['id'], unique=False)
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_paciente_dni', 'pacientes', ['dni'], unique=False)
    op.create_index('idx_paciente_telefono', 'pacientes', ['telefono'], unique=False)
    op.create_index(op.f('ix_pacientes_dni'), 'pacientes', ['dni'], unique=False)
    op.create_index(op.f('ix_pacientes_id'), 'pacientes', ['id'], unique=False)
    op.create_index(op.f('ix_pacientes_nombre'), 'pacientes', ['nombre'], unique=False)
    op.create_index(op.f('ix_pacientes_telefono'), 'pacientes', ['telefono'], unique=False)
    op.create_table('profesionales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('especialidades', sa.JSON(), nullable=True),
    sa.Column('horarios', sa.JSON(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profesionales_id'), 'profesionales', ['id'], unique=False)
    op.create_index(op.f('ix_profesionales_nombre'), 'profesionales', ['nombre'], unique=False)
    op.create_table('turnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_profesional', sa.Integer(), nullable=False),
    sa.Column('id_clinica', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['id_clinica'], ['clinicas.id'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['id_profesional'], ['profesionales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_turno_clinica_fecha', 'turnos', ['id_clinica', 'fecha_hora'], unique=False)
    op.create_index('idx_turno_estado_fecha', 'turnos', ['estado', 'fecha_hora'], unique=False)
    op.create_index('idx_turno_fecha_profesional', 'turnos', ['fecha_hora', 'id_profesional'], unique=False)
    op.create_index('idx_turno_paciente_fecha', 'turnos', ['id_paciente', 'fecha_hora'], unique=False)
    op.create_index(op.f('ix_turnos_estado'), 'turnos', ['estado'], unique=False)
    op.create_index(op.f('ix_turnos_fecha_hora'), 'turnos', ['fecha_hora'], unique=False)
    op.create_index(op.f('ix_turnos_id'), 'turnos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turnos_id'), table_name='turnos')
    op.drop_index(op.f('ix_turnos_fecha_hora'), table_name='turnos')
    op.drop_index(op.f('ix_turnos_estado'), table_name='turnos')
    op.drop_index('idx_turno_paciente_fecha', table_name='turnos')
    op.drop_index('idx_turno_fecha_profesional', table_name='turnos')
    op.drop_index('idx_turno_estado_fecha', table_name='turnos')
    op.drop_index('idx_turno_clinica_fecha', table_name='turnos')
    op.drop_table('turnos')
    op.drop_index(op.f('ix_profesionales_nombre'), table_name='profesionales')
    op.drop_index(op.f('ix_profesionales_id'), table_name='profesionales')
    op.drop_table('profesionales')
    op.drop_index(op.f('ix_pacientes_telefono'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_nombre'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_id'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_dni'), table_name='pacientes')
    op.drop_index('idx_paciente_telefono', table_name='pacientes')
    op.drop_index('idx_paciente_dni', table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_index(op.f('ix_logs_ia_id'), table_name='logs_ia')
    op.drop_index(op.f('ix_logs_ia_fecha'), table_name='logs_ia')
    op.drop_index('idx_log_fecha_confianza', table_name='logs_ia')
    op.drop_table('logs_ia')
    op.drop_index(op.f('ix_especialidades_nombre'), table_name='especialidades')
    op.drop_index(op.f('ix_especialidades_id'), table_name='especialidades')
    op.drop_index('idx_especialidad_nombre', table_name='especialidades')
    op.drop_table('especialidades')
    op.drop_index(op.f('ix_clinicas_nombre'), table_name='clinicas')
    op.drop_index(op.f('ix_clinicas_id'), table_name='clinicas')
    op.drop_index(op.f('ix_clinicas_did_whatsapp'), table_name='clinicas')
    op.drop_table('clinicas')
    # ### end Alembic commands ###
